const express=require('express'),path=require('path'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),cors=require('cors'),{Pool}=require('pg'),fs=require('fs'),app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'BASSAM_SPIRITUAL_SECRET_KEY_2026',pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:!1},max:10,connectionTimeoutMillis:15e3,idleTimeoutMillis:3e4});
pool.on('error',e=>console.error('❌ تجمع:',e.message));
app.use(cors()); app.use(express.json({limit:'10mb'})); app.use(express.static(path.join(__dirname,'public')));

const initDB=async()=>{try{
await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,full_name VARCHAR(255),email VARCHAR(255) UNIQUE,password VARCHAR(255),phone VARCHAR(50),role VARCHAR(50) DEFAULT 'user')`);
await pool.query(`CREATE TABLE IF NOT EXISTS requests(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id),fullname VARCHAR(255),email VARCHAR(255),userphone VARCHAR(50),servicetype VARCHAR(255),description TEXT,status VARCHAR(50) DEFAULT 'pending',createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,paymentmethod VARCHAR(100),payment_sender_name VARCHAR(255),payment_transfer_number VARCHAR(100),payment_rejection_reason TEXT,initial_diagnosis TEXT,treatment_plan TEXT,chat_closed BOOLEAN DEFAULT FALSE,last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
await pool.query(`CREATE TABLE IF NOT EXISTS messages(id SERIAL PRIMARY KEY,requestid INTEGER REFERENCES requests(id),senderid INTEGER,sendername VARCHAR(255),senderrole VARCHAR(50),messagetext TEXT,createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
await pool.query(`CREATE TABLE IF NOT EXISTS articles(id SERIAL PRIMARY KEY,title VARCHAR(255),summary TEXT,content TEXT,icon VARCHAR(100),createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
await pool.query(`CREATE TABLE IF NOT EXISTS reviews(id SERIAL PRIMARY KEY,userid INTEGER REFERENCES users(id),fullname VARCHAR(255),comment TEXT,rating INTEGER DEFAULT 5,isapproved BOOLEAN DEFAULT FALSE,createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
await pool.query(`CREATE TABLE IF NOT EXISTS ai_config(id SERIAL PRIMARY KEY,instructions TEXT)`);
const c=await pool.query(`SELECT COUNT(*) FROM ai_config`);if(parseInt(c.rows[0].count)===0)await pool.query(`INSERT INTO ai_config(instructions) VALUES($1)`,['أنت مستشار فقهي وروحاني معتمد في مركز النور الرباني.']);
await pool.query(`ALTER TABLE requests ADD COLUMN IF NOT EXISTS chat_closed BOOLEAN DEFAULT FALSE`);
await pool.query(`ALTER TABLE requests ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);  
console.log('✅ جداول جاهزة');
}catch(e){console.error('❌ تهيئة:',e.message)}}; initDB();

(async()=>{try{const e='alshameerybassam@gmail.com',r=await pool.query(`SELECT id FROM users WHERE email=$1`,[e]);if(r.rows.length===0)await pool.query(`INSERT INTO users(full_name,email,password,role) VALUES($1,$2,$3,$4)`,['الشيخ بسام',e,bcrypt.hashSync('bassam112358112358',8),'admin'])}catch(e){console.error('مدير:',e.message)}})();

const auth=(r,s,n)=>{const t=r.headers['authorization'];if(!t)return s.status(401).json({error:'غير مصرح'});const o=t.split(' ')[1];if(!o)return s.status(401).json({error:'غير مصرح'});try{r.user=jwt.verify(o,JWT_SECRET);n()}catch(e){return s.status(403).json({error:'جلسة منتهية'})}},admin=(r,s,n)=>{if(r.user.role!=='admin')return s.status(403).json({error:'للإدارة فقط'});n()};

app.post('/api/auth/register',async(r,s)=>{let{fullName:n,email:t,password:o,phone:i}=r.body;if(!n||!t||!o)return s.status(400).json({error:'جميع الحقول مطلوبة.'});try{let e=await pool.query(`SELECT id FROM users WHERE email=$1`,[t]);if(e.rows.length>0)return s.status(400).json({error:'البريد مسجل مسبقاً.'});await pool.query(`INSERT INTO users(full_name,email,password,phone) VALUES($1,$2,$3,$4)`,[n,t,bcrypt.hashSync(o,8),i]);s.json({success:!0})}catch(e){s.status(500).json({error:'خطأ تسجيل'})}});
app.post('/api/auth/login',async(r,s)=>{let{email:n,password:t}=r.body;if(!n||!t)return s.status(400).json({error:'البريد وكلمة المرور مطلوبان.'});try{let o=await pool.query(`SELECT * FROM users WHERE email=$1`,[n]);if(o.rows.length===0||!bcrypt.compareSync(t,o.rows[0].password))return s.status(400).json({error:'بيانات خاطئة.'});let i=o.rows[0],e=jwt.sign({id:i.id,email:i.email,role:i.role,full_name:i.full_name},JWT_SECRET,{expiresIn:'24h'});s.json({success:!0,token:e,user:{full_name:i.full_name,email:i.email,role:i.role}})}catch(e){s.status(500).json({error:'خطأ دخول'})}});
app.get('/api/auth/verify',auth,async(r,s)=>{let n=await pool.query(`SELECT id,full_name,email,role FROM users WHERE id=$1`,[r.user.id]);if(n.rows.length===0)return s.status(401).json({error:'جلسة غير صالحة.'});s.json({success:!0,user:n.rows[0]})});
app.post('/api/auth/forgot-password',async(r,s)=>{let{email:n}=r.body;if(!n)return s.status(400).json({error:'يرجى إدخال البريد الإلكتروني.'});let t=await pool.query(`SELECT id FROM users WHERE email=$1`,[n]);if(t.rows.length===0)return s.json({success:!0,message:'إذا كان مسجلاً سيرسل رابط.'});let o=jwt.sign({id:t.rows[0].id,email:n,type:'password_reset'},JWT_SECRET,{expiresIn:'1h'});s.json({success:!0,message:'تم الإرسال',resetLink:`https://bassam-spiritual-center.onrender.com/reset-password?token=${o}`})});
app.post('/api/auth/reset-password',async(r,s)=>{let{token:n,newPassword:t}=r.body;if(!n||!t)return s.status(400).json({error:'بيانات ناقصة.'});try{let o=jwt.verify(n,JWT_SECRET);if(o.type!=='password_reset')return s.status(400).json({error:'رمز غير صالح.'});await pool.query(`UPDATE users SET password=$1 WHERE id=$2`,[bcrypt.hashSync(t,8),o.id]);s.json({success:!0,message:'تم التغيير'})}catch(e){s.status(400).json({error:'رمز غير صالح'})}});
app.get('/reset-password',(r,s)=>{s.send(`<!DOCTYPE html><html lang="ar"><head><meta charset="UTF-8"><title>إعادة تعيين</title><meta name="viewport" content="width=device-width,initial-scale=1.0"><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap" rel="stylesheet"><style>body{font-family:'Cairo';background:#F4F6F9;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0}.box{background:#fff;border-radius:24px;box-shadow:0 20px 60px rgba(0,0,0,0.1);max-width:440px;width:100%;padding:40px 30px;border-top:6px solid #F5B041;text-align:center}.box input{width:100%;padding:12px;border:2px solid #E2E8F0;border-radius:12px;margin-bottom:15px;font-family:'Cairo'}.box button{width:100%;padding:14px;background:linear-gradient(135deg,#F5B041,#E67E22);color:#0A1628;border:none;border-radius:12px;font-weight:800;cursor:pointer}.msg{background:#27ae60;color:#fff;padding:15px;border-radius:12px;margin-bottom:15px;display:none}</style></head><body><div class="box"><h2 style="color:#0A1628">إعادة تعيين كلمة المرور</h2><div class="msg" id="msg"></div><form id="f"><input type="password" id="p" placeholder="كلمة المرور الجديدة" required minlength="6"><button type="submit">تغيير</button></form></div><script>const t=new URLSearchParams(location.search).get('token');if(!t){document.getElementById('msg').style.display='block';document.getElementById('msg').style.background='#e74c3c';document.getElementById('msg').textContent='رابط غير صالح.';document.getElementById('f').style.display='none'}document.getElementById('f').addEventListener('submit',async e=>{e.preventDefault();const r=await fetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:t,newPassword:document.getElementById('p').value})});const d=await r.json();const m=document.getElementById('msg');m.style.display='block';if(d.success){m.style.background='#27ae60';m.textContent='✅ تم التغيير.';setTimeout(()=>location.href='/login.html',2000)}else{m.style.background='#e74c3c';m.textContent='❌ '+(d.error||'خطأ')}})</script></body></html>`)});

app.get('/api/notifications',auth,async(r,s)=>{try{let n=r.user.id,t=r.user.role,o=[];if(t==='admin'){let i=await pool.query(`SELECT COUNT(*) FROM requests WHERE status='pending'`),e=await pool.query(`SELECT COUNT(*) FROM requests WHERE status='payment_submitted'`),u=await pool.query(`SELECT COUNT(*) FROM messages WHERE senderrole='user' AND requestid IN (SELECT id FROM requests WHERE status != 'closed')`);o.push({type:'pending_requests',count:parseInt(i.rows[0].count)});o.push({type:'payment_submitted',count:parseInt(e.rows[0].count)});o.push({type:'new_messages_admin',count:parseInt(u.rows[0].count)})}else{let i=await pool.query(`SELECT COUNT(*) FROM requests WHERE user_id=$1 AND status='accepted_waiting_payment'`,[n]),e=await pool.query(`SELECT COUNT(*) FROM requests WHERE user_id=$1 AND status='diagnosed'`,[n]),u=await pool.query(`SELECT COUNT(*) FROM messages WHERE requestid IN (SELECT id FROM requests WHERE user_id=$1) AND senderrole='admin'`,[n]);o.push({type:'accepted_waiting_payment',count:parseInt(i.rows[0].count)});o.push({type:'diagnosed',count:parseInt(e.rows[0].count)});o.push({type:'new_messages',count:parseInt(u.rows[0].count)})}s.json({success:!0,notifications:o})}catch(e){s.status(500).json({error:'خطأ إشعارات'})}});

const aiK=[{keywords:['عين','حسد','نظرة','حاسد','عاين','معيون'],replies:['🕌 العين حق…','🌿 للوقاية…','💧 اغتسل…']},{keywords:['سحر','مسحور','ساحر','عمل'],replies:['📖 السحر…','🛡️ لا تخف…','🌙 تذكر…']},{keywords:['مس','شيطان','جني','صرع','تلبس','وسواس'],replies:['🤲 المس…','🕋 استمع…','📿 لا تيأس…']},{keywords:['ضيق','حزن','اكتئاب','هم','غم','قلق','خوف'],replies:['💙 الضيق…','🌅 جرب…','🍃 لا تحمل…']},{keywords:['رؤيا','حلم','منام','تفسير'],replies:['🌙 الرؤى…','📖 قال النبي…','🕌 بإمكانك…']},{keywords:['زواج','عانس','عنوسة','تأخر زواج','زوج','زوجة'],replies:['💍 الزواج…','🌸 لا تستعجل…','🕌 أرسل طلبك…']},{keywords:['مرض','وجع','ألم','سرطان','سقم','عله'],replies:['🩺 الشفاء…','💊 نحن نكمل…','🌿 قال الله…']}],fallback=['🌙 السلام عليكم…','🕌 أهلاً بك…','📿 أنا هنا…','💡 يمكنني مساعدتك…'];
app.post('/api/ai-chat',async(r,s)=>{let n=r.body.message?.trim()||'';if(!n)return s.json({success:!0,reply:'تفضل، أنا بانتظار استفسارك.'});let t=n.toLowerCase();for(let o of aiK)for(let i of o.keywords)if(t.includes(i))return s.json({success:!0,reply:o.replies[Math.floor(Math.random()*o.replies.length)]});if(t.length<15)return s.json({success:!0,reply:'أرجو أن تعطيني تفاصيل أكثر…'});s.json({success:!0,reply:fallback[Math.floor(Math.random()*fallback.length)]})});

// لوحة المستفيد
app.get('/api/dashboard/me',auth,async(r,s)=>{try{let n=await pool.query(`SELECT id,user_id,fullname AS "fullName",email,userphone AS "userPhone",servicetype AS "serviceType",description,status,createdat AS "createdAt",paymentmethod AS "paymentMethod",payment_sender_name,payment_transfer_number,payment_rejection_reason,initial_diagnosis,treatment_plan,chat_closed FROM requests WHERE user_id=$1 ORDER BY createdat DESC`,[r.user.id]),t=await pool.query(`SELECT full_name,email,phone FROM users WHERE id=$1`,[r.user.id]);s.json({success:!0,user:t.rows[0],requests:n.rows})}catch(e){s.status(500).json({error:'خطأ بيانات'})}});
app.post('/api/dashboard/request',auth,async(r,s)=>{try{let{serviceType:n,description:t}=r.body;if(!t||t.trim().length<10)return s.status(400).json({success:!1,error:'وصف قصير'});let o=await pool.query(`SELECT full_name,email,phone FROM users WHERE id=$1`,[r.user.id]);if(o.rows.length===0)return s.status(404).json({success:!1,error:'مستخدم غير موجود'});let i=o.rows[0],e=await pool.query(`INSERT INTO requests(user_id,fullname,email,userphone,servicetype,description) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[r.user.id,i.full_name,i.email,i.phone,n,t]);s.json({success:!0,requestId:e.rows[0].id})}catch(e){s.status(500).json({success:!1,error:'خطأ داخلي'})}});
app.get('/api/dashboard/request/:id',auth,async(r,s)=>{let n=await pool.query(`SELECT id,user_id,fullname AS "fullName",email,userphone AS "userPhone",servicetype AS "serviceType",description,status,createdat AS "createdAt",paymentmethod AS "paymentMethod",payment_sender_name,payment_transfer_number,payment_rejection_reason,initial_diagnosis,treatment_plan,chat_closed FROM requests WHERE id=$1`,[r.params.id]);if(n.rows.length===0)return s.status(404).json({error:'غير موجود'});s.json(n.rows[0])});
app.put('/api/dashboard/request/:id/submit-payment',auth,async(r,s)=>{let{paymentMethod:n,paymentSenderName:t,paymentTransferNumber:o}=r.body;await pool.query(`UPDATE requests SET paymentmethod=$1,payment_sender_name=$2,payment_transfer_number=$3,status='payment_submitted',last_updated=CURRENT_TIMESTAMP WHERE id=$4`,[n,t,o,r.params.id]);s.json({success:!0})});
app.post('/api/dashboard/reviews',auth,async(r,s)=>{let{comment:n,rating:t}=r.body,o=await pool.query(`SELECT full_name FROM users WHERE id=$1`,[r.user.id]);await pool.query(`INSERT INTO reviews(userid,fullname,comment,rating) VALUES($1,$2,$3,$4)`,[r.user.id,o.rows[0].full_name,n,t]);s.json({success:!0})});

// لوحة المدير
app.get('/api/admin/requests',auth,admin,async(r,s)=>{let n=await pool.query(`SELECT id,user_id,fullname AS "fullName",email,userphone AS "userPhone",servicetype AS "serviceType",description,status,createdat AS "createdAt",paymentmethod AS "paymentMethod",payment_sender_name,payment_transfer_number,payment_rejection_reason,initial_diagnosis,treatment_plan,chat_closed FROM requests ORDER BY createdat DESC`);s.json(n.rows)});
app.put('/api/admin/requests/:id/accept-initial',auth,admin,async(r,s)=>{await pool.query(`UPDATE requests SET status='accepted_waiting_payment',last_updated=CURRENT_TIMESTAMP WHERE id=$1`,[r.params.id]);s.json({success:!0})});
app.put('/api/admin/requests/:id/reject-initial',auth,admin,async(r,s)=>{await pool.query(`UPDATE requests SET status='rejected',payment_rejection_reason=$1,last_updated=CURRENT_TIMESTAMP WHERE id=$2`,[r.body.reason||'بدون سبب',r.params.id]);s.json({success:!0})});
app.put('/api/admin/requests/:id/approve-payment',auth,admin,async(r,s)=>{await pool.query(`UPDATE requests SET status='processing',last_updated=CURRENT_TIMESTAMP WHERE id=$1`,[r.params.id]);s.json({success:!0})});
app.put('/api/admin/requests/:id/reject-payment',auth,admin,async(r,s)=>{await pool.query(`UPDATE requests SET status='payment_rejected',payment_rejection_reason=$1,last_updated=CURRENT_TIMESTAMP WHERE id=$2`,[r.body.reason||'بدون سبب',r.params.id]);s.json({success:!0})});
app.put('/api/admin/requests/:id/diagnose',auth,admin,async(r,s)=>{try{let{initial_diagnosis:n,treatment_plan:t}=r.body,o=r.params.id;await pool.query(`UPDATE requests SET initial_diagnosis=$1,treatment_plan=$2,status='diagnosed',last_updated=CURRENT_TIMESTAMP WHERE id=$3`,[n,t,o]);let i=await pool.query(`SELECT fullname FROM requests WHERE id=$1`,[o]);if(i.rows.length>0){let e=`📋 **تم تشخيص حالتك**\n\n🩺 التشخيص:\n${n||'لا يوجد'}\n\n📝 الخطة العلاجية:\n${t||'لا توجد'}`;await pool.query(`INSERT INTO messages(requestid,senderid,sendername,senderrole,messagetext) VALUES($1,$2,$3,$4,$5)`,[o,r.user.id,r.user.full_name,'admin',e])}s.json({success:!0})}catch(e){s.status(500).json({success:!1,error:'خطأ تشخيص'})}});
app.put('/api/admin/requests/:id/update-field',auth,admin,async(r,s)=>{try{let{field:n,value:t}=r.body;if(!n||!['initial_diagnosis','treatment_plan'].includes(n))return s.status(400).json({error:'حقل غير صالح'});await pool.query(`UPDATE requests SET ${n}=$1,last_updated=CURRENT_TIMESTAMP WHERE id=$2`,[t,r.params.id]);s.json({success:!0})}catch(e){s.status(500).json({error:'خطأ تحديث'})}});
app.put('/api/admin/requests/:id/toggle-chat',auth,admin,async(r,s)=>{try{let n=r.params.id,t=await pool.query(`SELECT chat_closed FROM requests WHERE id=$1`,[n]);if(t.rows.length===0)return s.status(404).json({error:'طلب غير موجود'});let o=!t.rows[0].chat_closed;await pool.query(`UPDATE requests SET chat_closed=$1,last_updated=CURRENT_TIMESTAMP WHERE id=$2`,[o,n]);s.json({success:!0,chat_closed:o})}catch(e){s.status(500).json({error:'خطأ محادثة'})}});

// المراسلات
app.get('/api/requests/:id/messages',auth,async(r,s)=>{let n=await pool.query(`SELECT id,requestid AS "requestId",senderid AS "senderId",sendername AS "senderName",senderrole AS "senderRole",messagetext AS "messageText",createdat AS "createdAt" FROM messages WHERE requestid=$1 ORDER BY createdat ASC`,[r.params.id]);s.json({success:!0,messages:n.rows})});
app.post('/api/requests/:id/messages',auth,async(r,s)=>{try{let{messageText:n}=r.body;if(r.user.role==='user'){let t=await pool.query(`SELECT chat_closed FROM requests WHERE id=$1`,[r.params.id]);if(t.rows.length>0&&t.rows[0].chat_closed)return s.status(403).json({error:'المحادثة مغلقة'})}await pool.query(`INSERT INTO messages(requestid,senderid,sendername,senderrole,messagetext) VALUES($1,$2,$3,$4,$5)`,[r.params.id,r.user.id,r.user.full_name,r.user.role,n]);await pool.query(`UPDATE requests SET last_updated=CURRENT_TIMESTAMP WHERE id=$1`,[r.params.id]);s.json({success:!0})}catch(e){s.status(500).json({error:'خطأ إرسال'})}});

// مقالات
app.get('/api/articles',async(r,s)=>{let n=await pool.query(`SELECT id,title,summary,content,icon,createdat AS "createdAt" FROM articles ORDER BY createdat DESC`);s.json(n.rows)});
app.post('/api/admin/articles',auth,admin,async(r,s)=>{let{title:n,summary:t,content:o}=r.body;await pool.query(`INSERT INTO articles(title,summary,content) VALUES($1,$2,$3)`,[n,t,o]);s.json({success:!0})});
app.put('/api/admin/articles/:id',auth,admin,async(r,s)=>{let{title:n,summary:t,content:o}=r.body;await pool.query(`UPDATE articles SET title=$1,summary=$2,content=$3,updatedat=CURRENT_TIMESTAMP WHERE id=$4`,[n,t,o,r.params.id]);s.json({success:!0})});
app.delete('/api/admin/articles/:id',auth,admin,async(r,s)=>{await pool.query(`DELETE FROM articles WHERE id=$1`,[r.params.id]);s.json({success:!0})});

// تقييمات
app.get('/api/reviews',async(r,s)=>{let n=await pool.query(`SELECT id,userid AS "userId",fullname AS "fullName",comment,rating,isapproved AS "isApproved",createdat AS "createdAt" FROM reviews WHERE isapproved=TRUE ORDER BY createdat DESC`);s.json(n.rows)});
app.get('/api/admin/reviews',auth,admin,async(r,s)=>{let n=await pool.query(`SELECT id,userid AS "userId",fullname AS "fullName",comment,rating,isapproved AS "isApproved",createdat AS "createdAt" FROM reviews ORDER BY createdat DESC`);s.json({success:!0,reviews:n.rows})});
app.post('/api/admin/reviews',auth,admin,async(r,s)=>{try{let{fullName:n,comment:t,rating:o,isApproved:i}=r.body;await pool.query(`INSERT INTO reviews(userid,fullname,comment,rating,isapproved) VALUES($1,$2,$3,$4,$5)`,[r.user.id,n||'مستفيد',t,o||5,i||!1]);s.json({success:!0})}catch(e){s.status(500).json({error:'خطأ إضافة تقييم'})}});
app.put('/api/admin/reviews/:id',auth,admin,async(r,s)=>{try{let{fullName:n,comment:t,rating:o,isApproved:i}=r.body;await pool.query(`UPDATE reviews SET fullname=$1,comment=$2,rating=$3,isapproved=$4,updatedat=CURRENT_TIMESTAMP WHERE id=$5`,[n,t,o,i,r.params.id]);s.json({success:!0})}catch(e){s.status(500).json({error:'خطأ تعديل'})}});
app.delete('/api/admin/reviews/:id',auth,admin,async(r,s)=>{await pool.query(`DELETE FROM reviews WHERE id=$1`,[r.params.id]);s.json({success:!0})});

// AI config
app.get('/api/admin/ai-instructions',auth,admin,async(r,s)=>{let n=await pool.query(`SELECT instructions FROM ai_config ORDER BY id DESC LIMIT 1`);s.json({success:!0,instructions:n.rows[0]?.instructions||''})});
app.put('/api/admin/ai-instructions',auth,admin,async(r,s)=>{await pool.query(`UPDATE ai_config SET instructions=$1`,[r.body.instructions]);s.json({success:!0})});

// مهندس
let engineer;try{engineer=require('./engineer')}catch(e){engineer={getAgent:()=>({name:'غير متوفر',execute:()=>Promise.resolve('⚠️ وحدة المهندس غير متوفرة.')})}}
const db={updatePassword:async(e,n)=>{await pool.query(`UPDATE users SET password=$1 WHERE email=$2`,[bcrypt.hashSync(n,8),e])},getDailyRequests:async(e)=>{let n=await pool.query(`SELECT fullname AS "fullName",servicetype AS "serviceType",status FROM requests WHERE DATE(createdat)=$1`,[e]);return n.rows},getWeeklyRequests:async()=>{let e=await pool.query(`SELECT fullname AS "fullName",servicetype AS "serviceType",status FROM requests WHERE createdat>=CURRENT_DATE-INTERVAL '7 days'`);return e.rows},getQuickStats:async()=>{let e=await pool.query(`SELECT COUNT(*) FROM requests`),n=await pool.query(`SELECT COUNT(*) FROM requests WHERE status='pending'`),t=await pool.query(`SELECT COUNT(*) FROM requests WHERE status IN ('processing','accepted_waiting_payment','payment_submitted')`),o=await pool.query(`SELECT COUNT(*) FROM requests WHERE status IN ('diagnosed','completed')`),i=await pool.query(`SELECT COUNT(*) FROM requests WHERE status='rejected'`);return{total:+e.rows[0].count,pending:+n.rows[0].count,processing:+t.rows[0].count,completed:+o.rows[0].count,rejected:+i.rows[0].count}},deleteRejectedRequests:async()=>{let e=await pool.query(`DELETE FROM requests WHERE status='rejected'`);return e.rowCount},createBackup:async()=>{let e=path.join(__dirname,'backups');if(!fs.existsSync(e))fs.mkdirSync(e);let n=path.join(e,`backup_${Date.now()}.json`),t=await pool.query(`SELECT * FROM users`),o=await pool.query(`SELECT * FROM requests`);fs.writeFileSync(n,JSON.stringify({users:t.rows,requests:o.rows}));return n}};
app.post('/api/admin/engineer-command',auth,admin,async(r,s)=>{let{command:n}=r.body;if(!n)return s.status(400).json({error:'يرجى إرسال أمر.'});try{let t=engineer.getAgent(n),o=await t.execute(n,db);s.json({success:!0,reply:o,agent:t.name})}catch(e){s.status(500).json({error:'فشل الأمر'})}});

// توجيه
app.get('/admin',(r,s)=>s.sendFile(path.join(__dirname,'public/admin.html')));
app.get('/dashboard',(r,s)=>s.sendFile(path.join(__dirname,'public/dashboard.html')));
app.get('/login',(r,s)=>s.sendFile(path.join(__dirname,'public/login.html')));
app.get('/register',(r,s)=>s.sendFile(path.join(__dirname,'public/register.html')));
app.get('*',(r,s)=>{if(r.path.startsWith('/api/'))return s.status(404).json({error:'المسار غير موجود'});s.sendFile(path.join(__dirname,'public/index.html'))});

app.listen(PORT,()=>console.log(`🚀 يعمل على ${PORT}`)).on('error',e=>{console.error('❌ فشل:',e.message);process.exit(1)});
